mychain:
  rest-mengwp: #  mengwp_2012@163.com 账号
    bizid: a00e36c5
    cipher-suit: ec
    rest-url: https://rest.baas.alipay.com
    access-id: IjWrQ7RKYCGCYZTH
    access-secret: access.key
    default-account: gusto_bluesky_test
    default-account-key: user.key
    default-account-pwd: Test@654321
    tenantid: YCGCYZTH
    read-file-from-ext: false
    account: 开发者配置
    kmsId: nNq7mjx4YCGCYZTH1617255074282

  rest:  #xuyifen@gustochain.com 账号    #gusto_nft_test
    bizid: a00e36c5
    cipher-suit: ec
    rest-url: https://rest.baas.alipay.com
    access-id: 6zq0YbTiKGPAQENO
    access-secret: access-gusto.key
    default-account: gusto_nft_test
    default-account-key: user-gusto.key
    default-account-pwd: Test@654321
    tenantid: KGPAQENO
    read-file-from-ext: false
    account: 开发者配置
    kmsId: nNq7mjx4YCGCYZTH1617255074282

  rest1:  #xuyifen@gustochain.com 账号    #gusto_test1
    bizid: a00e36c5
    cipher-suit: ec
    rest-url: https://rest.baas.alipay.com
    access-id: 6zq0YbTiKGPAQENO
    access-secret: access-gusto.key
    default-account: gusto_test1
    default-account-key: user-gusto.key
    default-account-pwd: Test@654321
    tenantid: KGPAQENO
    read-file-from-ext: false
    account: 开发者配置
    kmsId: Il726LGGKGPAQENO1624004353911
server:
   port: 8090
  
#  bizid: 开放联盟链的链ID
#  cipher-suit: 加密算法，ec表示采用椭圆曲线数字签名算法
#  rest-url: 访问开放联盟链的地址
#  access-id: *开发者需要替换* 替换为准备环境步骤申请AccessKey时返回的Access-id
#  access-secret: *开发者需要替换* 将access.key文件内容替换为准备环境步骤申请AccessKey时返回的密钥
#  default-account: *开发者需要替换* 创建账户时的账户名
#  default-account-key: *开发者需要替换* 创建账户时返回的私钥
#  default-account-pwd: *开发者需要替换* 创建账户时的密码
#  tenantid:*开发者需要替换* 租户id，可通过管理控制台>账户信息查看；发起账户是密钥托管的链账户时需要，非托管模式不需要该参数
#  read-file-from-ext: 表示读取配置文件的路径，默认为false，表示在resource目录下读取
#  account:为密钥托管账户账户名
#  kmsId:为密钥托管账户kmsidkey 可以在控制台
